sequenceDiagram
Title: 投票者の登録
participant OW AS オーナー
participant DAPPS
participant VT AS 投票者のリスト

OW ->>+ OW: 投票者の準備

OW ->>+ DAPPS: 投票者の登録
    DAPPS ->>+ VT: 投票者情報を記録
    VT -->>- DAPPS : 応答
DAPPS -->>- OW : 応答
