sequenceDiagram
Title: アンケート作成
participant OW AS オーナー
participant DAPPS AS Contract
participant CP AS アンケート情報

OW ->>+ OW: アンケートの準備

OW ->>+ DAPPS: アンケート作成
    DAPPS ->>+ CP: アンケートを登録
    CP -->>- DAPPS : 応答
DAPPS -->>- OW : 応答
