sequenceDiagram
Title: 投票
participant Voter AS 投票者
participant DAPPS
participant CP as キャンペーンのリスト
participant VT AS 投票者のリスト
participant RT AS 投票結果

Voter ->>+ Voter: どれに投票するか決める

Voter ->>+ DAPPS: 投票

    DAPPS ->>+ CP: キャンペーンの確認
    CP -->>- DAPPS : result

    DAPPS ->>+ VT: 投票者の確認
    VT -->>- DAPPS : 応答

    DAPPS ->>+ RT: 投票結果を保管
    RT -->>- DAPPS : 応答

DAPPS -->>- Voter : 応答
